import type {
  Agency,
  Developer,
  MarketIndicator,
  NewsArticle,
  Opportunity,
  Property,
} from "./types";

export const marketIndicators: MarketIndicator[] = [
  { label: "ROBOR 3M", value: "6.85%", change: "+0.12", trend: "up" },
  { label: "EUR/RON", value: "4.97", change: "-0.02", trend: "down" },
  { label: "Inflație RO", value: "5.3%", change: "-0.4", trend: "down" },
  { label: "Preț mediu m² București", value: "€2,450", change: "+3.2%", trend: "up" },
];

export const properties: Property[] = [
  {
    id: "1",
    slug: "penthouse-floreasca-lake",
    title: "Penthouse Floreasca Lake — Vedere Panoramică",
    description:
      "Penthouse exclusivist cu terasă de 120 mp, finisaje premium și vedere completă spre lac. Proiect finalizat 2024, certificat energie A.",
    price: 890000,
    currency: "EUR",
    location: "Floreasca",
    city: "București",
    property_type: "Penthouse",
    bedrooms: 4,
    bathrooms: 3,
    area_sqm: 285,
    image_url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
    aix_score: 9.2,
    score_explanation:
      "Locație premium, supply limitat, cerere crescută din segmentul luxury. Fundamentale solide pe termen lung.",
    investment_insight:
      "Potențial apreciere 8-12% anual în următorii 3 ani. Yield estimat din chirii premium: 4.2%.",
    features: ["Terasă 120mp", "Parcare 2 locuri", "Smart Home", "Concierge"],
    status: "active",
    featured: true,
  },
  {
    id: "2",
    slug: "vila-pipera-scandinavia",
    title: "Vilă Modernă Pipera — Scandinavia Residence",
    description:
      "Vilă cu design nordic, grădină 500 mp, piscină și zonă BBQ. Comunitate gated, acces rapid spre Băneasa.",
    price: 650000,
    currency: "EUR",
    location: "Pipera",
    city: "București",
    property_type: "Vilă",
    bedrooms: 5,
    bathrooms: 4,
    area_sqm: 340,
    image_url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80",
    aix_score: 8.7,
    score_explanation:
      "Zonă cu infrastructură în dezvoltare, cerere stabilă din familii high-net-worth.",
    investment_insight:
      "Excelent pentru locuire + apreciere. Comparabil cu Pipera Nord la preț cu 15% sub piață.",
    features: ["Piscină", "Grădină 500mp", "Gated Community", "Garaj dublu"],
    status: "active",
    featured: true,
  },
  {
    id: "3",
    slug: "apartament-herastrau-2-camere",
    title: "Apartament 2 Camere Herăstrău — Investiție",
    description:
      "Apartament complet mobilat, ideal pentru investiție Airbnb sau chirie corporate. ROI estimat 7.5%.",
    price: 185000,
    currency: "EUR",
    location: "Herăstrău",
    city: "București",
    property_type: "Apartament",
    bedrooms: 2,
    bathrooms: 1,
    area_sqm: 72,
    image_url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
    aix_score: 8.1,
    score_explanation:
      "Yield ridicat, locație cu cerere constantă din expats și corporații.",
    investment_insight:
      "Cash-on-cash return estimat 7.5% din chirie. Payback period ~11 ani.",
    features: ["Mobilat complet", "Parcare", "Balcon", "AC"],
    status: "active",
    featured: false,
  },
  {
    id: "4",
    slug: "spatiu-comercial-victoriei",
    title: "Spațiu Comercial Bulevardul Victoriei",
    description:
      "Spațiu ground floor, vitrină stradală, trafic pietonal intens. Contract chirie existent până 2028.",
    price: 420000,
    currency: "EUR",
    location: "Victoriei",
    city: "București",
    property_type: "Comercial",
    area_sqm: 180,
    image_url: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80",
    aix_score: 7.8,
    score_explanation:
      "Locație centrală cu lichiditate bună. Chiriaș stabil reduce riscul.",
    investment_insight: "Yield din chirie: 8.2% brut. Asset defensiv în portofoliu.",
    features: ["Vitrină stradală", "Chiriaș activ", "Renovare 2023"],
    status: "active",
    featured: false,
  },
  {
    id: "5",
    slug: "teren-corbeanca-residential",
    title: "Teren Rezidențial Corbeanca — 1,200 mp",
    description:
      "Teren intravilan cu PUD aprobat pentru 4 vile. Utilități la limita proprietății.",
    price: 95000,
    currency: "EUR",
    location: "Corbeanca",
    city: "Ilfov",
    property_type: "Teren",
    area_sqm: 1200,
    image_url: "https://images.unsplash.com/photo-1500382017468-90403fed3eff?w=800&q=80",
    aix_score: 7.2,
    score_explanation:
      "Expansiune urbană spre nord. PUD aprobat reduce riscul de dezvoltare.",
    investment_insight:
      "Potențial dezvoltator: ROI 25-35% la exit după construcție.",
    features: ["PUD aprobat", "Utilități", "Drum asfaltat"],
    status: "active",
    featured: false,
  },
  {
    id: "6",
    slug: "apartament-primaverii-luxury",
    title: "Apartament 3 Camere Primăverii — Luxury",
    description:
      "Apartament în clădire boutique, 3 camere + dressing, finisaje marmură și lemn masiv.",
    price: 520000,
    currency: "EUR",
    location: "Primăverii",
    city: "București",
    property_type: "Apartament",
    bedrooms: 3,
    bathrooms: 2,
    area_sqm: 145,
    image_url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
    aix_score: 9.0,
    score_explanation:
      "Primăverii rămâne cel mai stabil segment luxury din București. Supply extrem de limitat.",
    investment_insight:
      "Asset de păstrare pe termen lung. Apreciere istorică 6-9% anual.",
    features: ["Dressing", "Marmură", "Parcare subterană", "Security 24/7"],
    status: "active",
    featured: true,
  },
];

export const newsArticles: NewsArticle[] = [
  {
    id: "1",
    slug: "bnr-dobanda-referinta-2026",
    title: "BNR menține dobânda de referință la 6.50% — Impact asupra pieței imobiliare",
    summary:
      "AiX Summary: Banca Națională a României a decis menținerea dobânzii de referință, semnalând stabilitate pe termen scurt pentru creditele ipotecare. Decizia favorizează pe moment stabilitatea pieței.",
    category: "Finance",
    image_url: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80",
    aix_score: 8.5,
    score_explanation:
      "Decizie BNR afectează direct costul finanțării și cererea imobiliară.",
    investment_insight:
      "Investitorii cu finanțare aprobată ar trebui să profite de fereastra actuală. Cumpărătorii cash câștigă putere de negociere.",
    status: "published",
    published_at: "2026-06-25T10:00:00Z",
  },
  {
    id: "2",
    slug: "pipera-nord-dezvoltare-infrastructura",
    title: "Pipera Nord: Noi proiecte de infrastructură acceleratează aprecierea",
    summary:
      "AiX Summary: Primăria a aprobat extinderea rețelei de transport și noi legături cu DN1, ceea ce va reduce timpul de navetă cu 20% și va crește valoarea proprietăților din proximitate.",
    category: "Construction",
    image_url: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80",
    aix_score: 7.8,
    score_explanation:
      "Infrastructura este driver principal de apreciere în zonele periurbane.",
    investment_insight:
      "Zonele din proximitatea noilor noduri de transport vor beneficia primul. Window de oportunitate: 12-18 luni.",
    status: "published",
    published_at: "2026-06-24T14:30:00Z",
  },
  {
    id: "3",
    slug: "segment-luxury-bucuresti-q2-2026",
    title: "Segmentul luxury București: +12% YoY — Supply record de livrări în Q3",
    summary:
      "AiX Summary: Peste 800 de unități premium vor fi livrate în Q3 2026. Cererea din segmentul €500K+ rămâne robustă, confirmând soliditatea acestui sector chiar și cu o ofertă în creștere.",
    category: "Luxury",
    image_url: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80",
    aix_score: 8.2,
    score_explanation:
      "Dinamica supply/demand în luxury determină pricing power pe termen mediu.",
    investment_insight:
      "Evită proiectele fără diferențiere. Focus pe locații cu supply limitat: Primăverii, Floreasca, Herăstrău.",
    status: "published",
    published_at: "2026-06-23T09:00:00Z",
  },
  {
    id: "4",
    slug: "robor-scade-usor-iunie",
    title: "ROBOR 3M scade ușor la 6.85% — Semnal pozitiv pentru piața creditelor",
    summary:
      "AiX Summary: Indicele ROBOR continuă tendința descendentă ușoară, oferind respiro cumpărătorilor cu credite variabile și putând stimula ușor cererea de creditare ipotecară în perioada următoare.",
    category: "Finance",
    image_url: "https://images.unsplash.com/photo-1554224311-9b9459a08667?w=800&q=80",
    aix_score: 7.5,
    score_explanation: "ROBOR influențează direct rata lunară a creditelor ipotecare.",
    investment_insight:
      "Monitorizează refinanțarea dacă ești la rată variabilă. Fix rate devine mai atractiv sub 7%.",
    status: "published",
    published_at: "2026-06-22T11:00:00Z",
  },
];

export const developers: Developer[] = [
  {
    id: "1",
    slug: "one-united-properties",
    name: "One United Properties",
    description: "Liderul pieței imobiliare premium și sustenabile din România. Portofoliu extins de proiecte rezidențiale de lux și clădiri de birouri verzi în București.",
    aix_score: 9.1,
    score_explanation: "Track record impecabil de livrări, acces sporit la piața de capital și brand extrem de puternic pe plan local.",
    projects_count: 15,
    city: "București",
    status: "elite",
    country: "România",
    cities: ["București", "Constanța"],
    property_types: ["Apartament", "Penthouse", "Birou"],
    projects_list: ["One Herăstrău Park", "One Floreasca Towers", "One Cotroceni Park", "One Lake Club"],
    sector: "luxury",
    website: "https://www.one.ro",
  },
  {
    id: "2",
    slug: "emaar-properties",
    name: "Emaar Properties",
    description: "Dezvoltatorul de referință din Dubai, renumit pentru modelarea orizontului urban al emiratului, inclusiv Burj Khalifa și Dubai Mall.",
    aix_score: 9.5,
    score_explanation: "Dimensiune globală, portofoliu diversificat, rating suveran ridicat și randamente istorice excelente.",
    projects_count: 85,
    city: "Dubai",
    status: "elite",
    country: "Dubai",
    cities: ["Dubai", "Abu Dhabi"],
    property_types: ["Penthouse", "Vilă", "Residence", "Apartament"],
    projects_list: ["Downtown Dubai", "Dubai Marina", "Emaar Beachfront", "Arabian Ranches"],
    sector: "luxury",
    website: "https://www.emaar.com",
  },
  {
    id: "3",
    slug: "pastor-group",
    name: "Pastor Group",
    description: "Sinonim cu imobiliarele de lux din Monaco. Grupul construiește și deține unele dintre cele mai exclusiviste proprietăți rezidențiale de pe coastă.",
    aix_score: 9.7,
    score_explanation: "Monopol de facto pe segmentul ultra-luxury din Monaco, supply extrem de restricționat, conservare perfectă a valorii.",
    projects_count: 14,
    city: "Monte-Carlo",
    status: "elite",
    country: "Monaco",
    cities: ["Monte-Carlo", "La Condamine"],
    property_types: ["Penthouse", "Luxury Apartment", "Villa"],
    projects_list: ["Le Simona", "Le Stella", "Le Florestan"],
    sector: "luxury",
    website: "https://www.groupepastor.mc",
  },
  {
    id: "4",
    slug: "damac-properties",
    name: "DAMAC Properties",
    description: "Dezvoltator major din Dubai specializat în comunități rezidențiale premium de tip resort și turnuri branded luxury în parteneriat cu Fendi, Cavalli și de GRISOGONO.",
    aix_score: 9.2,
    score_explanation: "Focus clar pe branded design, rețea globală de clienți, strategii de marketing de înalt impact.",
    projects_count: 42,
    city: "Dubai",
    status: "elite",
    country: "Dubai",
    cities: ["Dubai"],
    property_types: ["Penthouse", "Villa", "Apartment"],
    projects_list: ["DAMAC Hills", "Cavalli Tower", "Canal Crown", "DAMAC Lagoons"],
    sector: "luxury",
    website: "https://www.damacproperties.com",
  },
  {
    id: "5",
    slug: "speedwell",
    name: "Speedwell",
    description: "Dezvoltator belgian axat pe proiecte mixte sustenabile (rezidențial, birouri, retail) în principalele hub-uri economice din România.",
    aix_score: 8.8,
    score_explanation: "Standard ridicat de construcție, design european modern, atenție deosebită la amplasarea urbană.",
    projects_count: 6,
    city: "București",
    status: "premium",
    country: "România",
    cities: ["București", "Cluj-Napoca", "Timișoara"],
    property_types: ["Apartament", "Birou", "Retail"],
    projects_list: ["The Ivy", "Triad Gardens", "Paltim", "Record Park"],
    sector: "mixed-use",
    website: "https://speedwell.be",
  },
  {
    id: "6",
    slug: "sobha-realty",
    name: "Sobha Realty",
    description: "Renumit pentru calitatea execuției (vertical integration) și finisajele de lux realizate in-house în proiectele sale signature din Dubai.",
    aix_score: 9.3,
    score_explanation: "Control 100% asupra designului și construcției, yield-uri excelente pe termen mediu și scurt.",
    projects_count: 22,
    city: "Dubai",
    status: "elite",
    country: "Dubai",
    cities: ["Dubai"],
    property_types: ["Villa", "Apartment", "Townhouse"],
    projects_list: ["Sobha Hartland", "Sobha One", "The S Tower"],
    sector: "luxury",
    website: "https://www.sobharealty.com",
  },
  {
    id: "7",
    slug: "impact-developer",
    name: "Impact Developer & Contractor",
    description: "Unul dintre primii dezvoltatori imobiliari din România post-decembristă, cunoscut pentru cartiere rezidențiale de mari dimensiuni (Greenfield).",
    aix_score: 7.4,
    score_explanation: "Prezență îndelungată pe piață, proiecte de anvergură medie-mare, dar penalizat la capitolele finisaje ultra-luxury și sustenabilitate avansată.",
    projects_count: 8,
    city: "București",
    status: "premium",
    country: "România",
    cities: ["București", "Constanța", "Iași"],
    property_types: ["Apartament", "Vilă"],
    projects_list: ["Greenfield Plumbuita", "Boreal Plus", "Greenfield Băneasa"],
    sector: "mid",
    website: "https://www.impactsa.ro",
  },
  {
    id: "8",
    slug: "granvia-residence",
    name: "Granvia Residence",
    description: "Dezvoltator spaniol activ în România, specializat în reconversia platformelor industriale în ansambluri rezidențiale urbane accesibile.",
    aix_score: 7.1,
    score_explanation: "Optimizarea spațiului urban, prețuri competitive pe segmentul mediu, istoric solid de livrări în București.",
    projects_count: 5,
    city: "București",
    status: "active",
    country: "România",
    cities: ["București", "Brașov"],
    property_types: ["Apartament"],
    projects_list: ["Granvia Park", "Granvia Marina", "Aviatorilor Residence"],
    sector: "mid",
    website: "https://www.granvia.ro",
  },
  {
    id: "9",
    slug: "skanska-europe",
    name: "Skanska Europe",
    description: "Grup suedez lider mondial în construcții și dezvoltare imobiliară, pionier în clădiri comerciale verzi și spații de birouri de clasa A în Europa.",
    aix_score: 9.0,
    score_explanation: "Standarde ESG extrem de stricte, inovații tehnologice de top și solvabilitate financiară absolută.",
    projects_count: 50,
    city: "Stockholm",
    status: "elite",
    country: "Europe",
    cities: ["Stockholm", "București", "Varșovia", "Praga"],
    property_types: ["Office Building", "Commercial Hub"],
    projects_list: ["Equilibrium", "Campus 6", "Spark", "Green Court"],
    sector: "commercial",
    website: "https://group.skanska.com",
  },
  {
    id: "10",
    slug: "bouygues-immobilier",
    name: "Bouygues Immobilier",
    description: "Filiala imobiliară a gigantului industrial francez Bouygues, operând în Europa cu un focus pe cartiere sustenabile cu amprentă redusă de carbon.",
    aix_score: 8.9,
    score_explanation: "Capacitate masivă de execuție, expertiză în parteneriate public-private și management inteligent al resurselor energetice.",
    projects_count: 120,
    city: "Paris",
    status: "elite",
    country: "Europe",
    cities: ["Paris", "Lyon", "Bruxelles", "Monaco"],
    property_types: ["Apartament", "Birou", "Eco-district"],
    projects_list: ["EcoQuartier Ginko", "Neo-C", "L'Avance"],
    sector: "mixed-use",
    website: "https://www.bouygues-immobilier.com",
  },
  {
    id: "11",
    slug: "emaar-europe",
    name: "Emaar Europe Division",
    description: "Divizia europeană a Emaar Properties, responsabilă de investiții strategice în active hoteliere și ansambluri mixte ultra-premium din marile capitale europene.",
    aix_score: 9.2,
    score_explanation: "Sinergie cu rețeaua din Orientul Mijlociu, capital robust și branding exclusiv.",
    projects_count: 12,
    city: "Londra",
    status: "elite",
    country: "Europe",
    cities: ["Londra", "Milano", "Monaco"],
    property_types: ["Luxury Hotel", "Branded Residence"],
    projects_list: ["Address Hotel London", "Emaar Milano Residences"],
    sector: "luxury",
    website: "https://www.emaar.com",
  },
  {
    id: "12",
    slug: "marzocco-group",
    name: "Marzocco Group",
    description: "Grup imobiliar de elită din Monaco, celebru pentru realizarea Turnului Odeon (Tour Odeon), un simbol al arhitecturii contemporane de pe Riviera Franceză.",
    aix_score: 9.8,
    score_explanation: "Creatori ai unora dintre cele mai scumpe apartamente din lume, finisaje artizanale de lux extrem și integrare tehnologică aeronautică.",
    projects_count: 8,
    city: "Monte-Carlo",
    status: "elite",
    country: "Monaco",
    cities: ["Monte-Carlo"],
    property_types: ["Ultra-Luxury Penthouse", "Sky Villa"],
    projects_list: ["Tour Odeon", "Testimonio II", "Villa de l'Annonciade"],
    sector: "luxury",
    website: "https://www.marzocco.mc",
  },
];

export const agencies: Agency[] = [
  {
    id: "1",
    slug: "cristian-vaduva-real-estate",
    name: "Cristian Vaduva Real Estate",
    description:
      "Buyer representation, luxury properties și market intelligence. Parte din ecosistemul AiX OS™.",
    website: "https://cristianvaduva.com",
    phone: "+43 650 953 6345",
    email: "cristianvaduva@duck.com",
    city: "București",
    aix_score: 9.5,
    properties_count: 45,
    status: "active",
    specializations: ["Buyer Representation", "Market Intelligence", "Luxury Properties"],
    collaboration_info: "Disponibil pentru co-exclusivitate și referral agreements."
  },
  {
    id: "2",
    slug: "aixluxury-properties",
    name: "AiX Luxury Properties",
    description:
      "Specialiști în proprietăți premium, off-market deals și investiții internaționale.",
    website: "https://aixluxury.com",
    phone: "+40 700 000 000",
    email: "info@aixluxury.com",
    city: "București",
    aix_score: 9.2,
    properties_count: 38,
    status: "active",
    specializations: ["Off-Market Deals", "Investiții Internaționale", "Proprietăți Premium"],
    collaboration_info: "Colaborare exclusivă prin rețeaua AiX OS™."
  },
  {
    id: "3",
    slug: "premium-estates-ro",
    name: "Premium Estates Romania",
    description:
      "Agenție boutique focusată pe segmentul €300K+, cu rețea internațională de cumpărători.",
    website: "https://premiumestates.ro",
    city: "București",
    aix_score: 8.3,
    properties_count: 22,
    status: "active",
    specializations: ["Boutique Agency", "Segment €300K+", "Rețea Internațională"],
    collaboration_info: "Deschis la colaborare pentru proprietăți listate exclusiv."
  },
  {
    id: "4",
    slug: "chestertons",
    name: "Chestertons",
    description:
      "Lider global în real estate luxury cu peste 200 de ani de experiență și prezență pe 5 continente.",
    website: "https://chestertons.com",
    phone: "+44 20 7111 1111",
    email: "info@chestertons.com",
    city: "Londra",
    aix_score: 9.7,
    properties_count: 1500,
    status: "active",
    specializations: ["Ultra-Luxury", "Global Network", "Property Management"],
    collaboration_info: "Partener oficial global pentru proprietăți ultra-luxury."
  },
];

export const opportunities: Opportunity[] = [
  {
    id: "1",
    slug: "off-market-floreasca-triplex",
    title: "Off-Market Triplex Floreasca — Sub preț de piață",
    description:
      "Triplex 320 mp, vândut discret de proprietar. Preț cu 12% sub comparabile. Disponibil 14 zile.",
    opportunity_type: "Off-Market",
    location: "Floreasca, București",
    min_investment: 720000,
    currency: "EUR",
    expected_yield: 4.5,
    aix_score: 9.3,
    score_explanation:
      "Preț sub piață, locație premium, vânzare motivată — factori rari simultan.",
    investment_insight:
      "Negociere suplimentară posibilă 3-5%. Recomandare: due diligence rapid, rezervare cu avans.",
    image_url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
    status: "active",
    featured: true,
  },
  {
    id: "2",
    slug: "development-corbeanca-4-vile",
    title: "Dezvoltare 4 Vile Corbeanca — PUD Aprobat",
    description:
      "Teren 4,800 mp cu PUD aprobat. Cost construcție estimat €1.2M, valoare exit €2.1M.",
    opportunity_type: "Dezvoltare",
    location: "Corbeanca, Ilfov",
    min_investment: 350000,
    currency: "EUR",
    expected_yield: 28,
    aix_score: 8.5,
    score_explanation:
      "PUD aprobat reduce riscul regulamentar. ROI proiectat peste media pieței.",
    investment_insight:
      "Parteneriat cu dezvoltator local recomandat. Timeline: 18-24 luni.",
    image_url: "https://images.unsplash.com/photo-1500382017468-90403fed3eff?w=800&q=80",
    status: "active",
    featured: true,
  },
  {
    id: "3",
    slug: "portfolio-chirii-corporate-herastrau",
    title: "Portofoliu 3 Apartamente Herăstrău — Chirie Corporate",
    description:
      "Pachet 3 apartamente mobilate, contracte corporate active, yield 7.8% brut.",
    opportunity_type: "Portofoliu",
    location: "Herăstrău, București",
    min_investment: 520000,
    currency: "EUR",
    expected_yield: 7.8,
    aix_score: 8.8,
    score_explanation:
      "Yield stabil, chiriași corporate, diversificare pe 3 unități.",
    investment_insight:
      "Ideal pentru investitori care caută cash flow, nu speculație.",
    image_url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
    status: "active",
    featured: false,
  },
];
