import {
  Brain,
  Building2,
  Activity,
  Coins,
  Shield,
  Scale,
  Cpu,
  Lock,
  Sparkles,
  BookOpen,
  Wrench,
  Search,
  Users,
  Compass,
  TrendingUp,
  Map,
  DollarSign,
  Newspaper,
  Eye,
  FileText,
  Gem,
  Calculator,
  MessageCircle,
  Mail,
  Send,
  Plane,
  Car,
  Ship,
  Globe,
  Network,
  type LucideIcon
} from "lucide-react";

export interface ServiceItem {
  id: string;
  label: string;
  labelEn: string;
  desc: string;
  descEn: string;
  href: string;
  icon: LucideIcon;
  keywords: string[];
  category: "BUY_SELL" | "INVEST_PROTECT" | "LEARN_RESEARCH" | "TOOLS" | "AI_SYSTEM" | "LUXURY_TRAVEL";
  status: "active" | "hidden" | "beta";
  actionLabel?: string;
  actionLabelEn?: string;
  external?: boolean;
}

export const ALL_SERVICES_REGISTRY: ServiceItem[] = [
  // ─── BUY & SELL ───────────────────────────────────────────────────────────
  {
    id: "properties",
    label: "Properties",
    labelEn: "Properties",
    desc: "Catalog complet de proprietăți premium selectate.",
    descEn: "Complete catalog of curated premium properties.",
    href: "/proprietati",
    icon: Building2,
    keywords: ["proprietati", "properties", "apartamente", "vile", "case"],
    category: "BUY_SELL",
    status: "active",
    actionLabel: "Explorează",
    actionLabelEn: "Explore",
  },
  {
    id: "developers",
    label: "Developers",
    labelEn: "Developers",
    desc: "Profilele și ratingul de siguranță al constructorilor.",
    descEn: "Builder profiles and structural safety ratings.",
    href: "/dezvoltatori",
    icon: Users,
    keywords: ["dezvoltatori", "developers", "constructori"],
    category: "BUY_SELL",
    status: "active",
    actionLabel: "Audit",
    actionLabelEn: "Audit",
  },
  {
    id: "agencies",
    label: "Agencies",
    labelEn: "Agencies",
    desc: "Agenții de consultanță imobiliară partenere.",
    descEn: "Verified partner real estate consultancies.",
    href: "/agentii",
    icon: Compass,
    keywords: ["agentii", "agencies", "brokeri"],
    category: "BUY_SELL",
    status: "active",
    actionLabel: "Vezi",
    actionLabelEn: "View",
  },
  {
    id: "buyer-rep",
    label: "Buyer Representation",
    labelEn: "Buyer Representation",
    desc: "Consultanță dedicată exclusiv cumpărătorului.",
    descEn: "Dedicated guidance exclusively for property buyers.",
    href: "/buyer",
    icon: Compass,
    keywords: ["buyer", "rep", "cumparator"],
    category: "BUY_SELL",
    status: "active",
    actionLabel: "Angajează",
    actionLabelEn: "Hire",
  },
  {
    id: "seller-rep",
    label: "Seller Representation",
    labelEn: "Seller Representation",
    desc: "Strategii avansate de marketing și vânzare.",
    descEn: "Advanced marketing and listings sale strategies.",
    href: "/seller",
    icon: TrendingUp,
    keywords: ["seller", "vinde", "vanzator"],
    category: "BUY_SELL",
    status: "active",
    actionLabel: "Listează",
    actionLabelEn: "List",
  },
  {
    id: "off-market",
    label: "Off Market",
    labelEn: "Off Market",
    desc: "Portal discret de tranzacții sub NDA.",
    descEn: "Discrete private listings registry under NDA.",
    href: "/off-market",
    icon: Lock,
    keywords: ["off-market", "privat", "confidential"],
    category: "BUY_SELL",
    status: "active",
    actionLabel: "Accesează",
    actionLabelEn: "Access",
  },

  // ─── INVEST & PROTECT ──────────────────────────────────────────────────────
  {
    id: "market-pulse",
    label: "Market Pulse",
    labelEn: "Market Pulse",
    desc: "Indicatori macroeconomici, analize și evoluții BNR.",
    descEn: "BNR macroeconomic indicators, analysis, and indices.",
    href: "/stiri",
    icon: Activity,
    keywords: ["market", "pulse", "stiri", "inflatie", "bnr"],
    category: "INVEST_PROTECT",
    status: "active",
    actionLabel: "Citește",
    actionLabelEn: "Read",
  },
  {
    id: "aix-score",
    label: "AiX Score",
    labelEn: "AiX Score",
    desc: "Rating proprietar de risc și sustenabilitate al activelor.",
    descEn: "Proprietary risk and asset safety scoring system.",
    href: "/aix-score",
    icon: Sparkles,
    keywords: ["score", "rating", "aix", "risc"],
    category: "INVEST_PROTECT",
    status: "active",
    actionLabel: "Vezi",
    actionLabelEn: "View",
  },
  {
    id: "investments",
    label: "Investments",
    labelEn: "Investments",
    desc: "Managementul portofoliilor UHNW și plasamente globale.",
    descEn: "Wealth management portfolios and global allocations.",
    href: "/investments",
    icon: Coins,
    keywords: ["investitii", "investments", "crypto", "etf"],
    category: "INVEST_PROTECT",
    status: "active",
    actionLabel: "Gestionează",
    actionLabelEn: "Manage",
  },
  {
    id: "private-wealth",
    label: "Private Wealth",
    labelEn: "Private Wealth",
    desc: "Ghiduri fiscale, optimizare taxe și calendar economic.",
    descEn: "Tax guidelines, optimizations, and private investor calendar.",
    href: "/wealth",
    icon: DollarSign,
    keywords: ["wealth", "private", "avere", "calendar"],
    category: "INVEST_PROTECT",
    status: "active",
    actionLabel: "Cercetează",
    actionLabelEn: "Research",
  },
  {
    id: "insurance",
    label: "Insurance",
    labelEn: "Insurance",
    desc: "Polițe de asigurare facultative și estimări de primă.",
    descEn: "Optional property insurance coverage & PAD estimates.",
    href: "/insurance",
    icon: Shield,
    keywords: ["asigurare", "insurance", "pad"],
    category: "INVEST_PROTECT",
    status: "active",
    actionLabel: "Calculează",
    actionLabelEn: "Calculate",
  },
  {
    id: "law",
    label: "RO Law",
    labelEn: "RO Law",
    desc: "Consultare juridică, contracte și limitări notariale.",
    descEn: "Legal framework, templates, and notary cost schedules.",
    href: "/law",
    icon: Scale,
    keywords: ["law", "lege", "legal", "notar"],
    category: "INVEST_PROTECT",
    status: "active",
    actionLabel: "Verifică",
    actionLabelEn: "Verify",
  },
  {
    id: "anti-teapa",
    label: "AntiȚeapă AI",
    labelEn: "AntiȚeapă AI",
    desc: "Sistem automat de de-riscare a tranzacțiilor.",
    descEn: "Automated scan mapping and risk mitigation software.",
    href: "/anti-teapa",
    icon: Shield,
    keywords: ["anti-teapa", "scanare", "litigii", "sarcini"],
    category: "INVEST_PROTECT",
    status: "active",
    actionLabel: "Auditează",
    actionLabelEn: "Audit",
  },
  {
    id: "oportunitati",
    label: "Opportunities",
    labelEn: "Opportunities",
    desc: "Oportunități de plasament direct off-market.",
    descEn: "High-yield private placement deals catalog.",
    href: "/oportunitati",
    icon: TrendingUp,
    keywords: ["oportunitati", "investitii", "deals"],
    category: "INVEST_PROTECT",
    status: "active",
    actionLabel: "Vezi Deal-uri",
    actionLabelEn: "View Deals",
  },
  {
    id: "network",
    label: "Private Network",
    labelEn: "Private Network",
    desc: "Acces în rețeaua discretă de investitori UHNW.",
    descEn: "Secure private messaging room and networking lobby.",
    href: "/network",
    icon: Network,
    keywords: ["network", "retea", "privata", "uhnw"],
    category: "INVEST_PROTECT",
    status: "active",
    actionLabel: "Accesează",
    actionLabelEn: "Access",
  },

  // ─── LEARN & RESEARCH ──────────────────────────────────────────────────────
  {
    id: "books",
    label: "Books",
    labelEn: "Books",
    desc: "Recomandări de cărți de negociere și analiză macro.",
    descEn: "Recommended reading checklist for high-stakes business.",
    href: "/books",
    icon: BookOpen,
    keywords: ["books", "carti", "voss", "psychology"],
    category: "LEARN_RESEARCH",
    status: "active",
    actionLabel: "Deschide",
    actionLabelEn: "Open",
  },
  {
    id: "learning",
    label: "Education",
    labelEn: "Education",
    desc: "Cursuri și educație financiară pentru investitori.",
    descEn: "Tutorial guides and courses for strategic investors.",
    href: "/learning",
    icon: BookOpen,
    keywords: ["education", "educatie", "ghiduri"],
    category: "LEARN_RESEARCH",
    status: "active",
    actionLabel: "Începe",
    actionLabelEn: "Start",
  },
  {
    id: "guides",
    label: "Guides",
    labelEn: "Guides",
    desc: "Checklisturi de achiziție, ghiduri practice ANAF.",
    descEn: "Acquisitions guide books and tax calculators.",
    href: "/learning",
    icon: BookOpen,
    keywords: ["guides", "ghiduri", "taxe"],
    category: "LEARN_RESEARCH",
    status: "active",
    actionLabel: "Accesează",
    actionLabelEn: "Access",
  },
  {
    id: "resources",
    label: "Resources",
    labelEn: "Resources",
    desc: "Baze de date, utilitare cadastrale externe și portaluri stat.",
    descEn: "State directories and external cadastre lookup resources.",
    href: "/resources",
    icon: Globe,
    keywords: ["resurse", "resources", "linkuri"],
    category: "LEARN_RESEARCH",
    status: "active",
    actionLabel: "Vezi",
    actionLabelEn: "View",
  },
  {
    id: "technology",
    label: "Technology",
    labelEn: "Technology",
    desc: "API documentation, integrations, and server status.",
    descEn: "API documentation, integrations, and server status.",
    href: "/technology",
    icon: Cpu,
    keywords: ["technology", "tehnologie", "api"],
    category: "LEARN_RESEARCH",
    status: "active",
    actionLabel: "Vezi Tech",
    actionLabelEn: "View Tech",
  },
  {
    id: "despre",
    label: "About Us",
    labelEn: "About Us",
    desc: "Misiunea, valorile și echipa din spatele platformei.",
    descEn: "Our mission statement, guidelines, and background.",
    href: "/despre",
    icon: Users,
    keywords: ["about", "despre", "echipa"],
    category: "LEARN_RESEARCH",
    status: "active",
  },
  {
    id: "contact-service",
    label: "Contact Support",
    labelEn: "Contact Support",
    desc: "Formular suport clienți, birouri și asistență directă.",
    descEn: "Customer support routing board and contacts.",
    href: "/contact",
    icon: Mail,
    keywords: ["contact", "suport"],
    category: "LEARN_RESEARCH",
    status: "active",
  },

  // ─── TOOLS ─────────────────────────────────────────────────────────────────
  {
    id: "calculators",
    label: "Calculators",
    labelEn: "Calculators",
    desc: "Calculatoare credite imobiliare și rate dobândă.",
    descEn: "Comprehensive home loan and credit interest calculators.",
    href: "/calculators",
    icon: Calculator,
    keywords: ["calculators", "calculatoare", "notar", "ipotecar"],
    category: "TOOLS",
    status: "active",
    actionLabel: "Calculează",
    actionLabelEn: "Calculate",
  },
  {
    id: "apps",
    label: "Open Apps",
    labelEn: "Open Apps",
    desc: "Generatoare text, convertoare, JSON validator local.",
    descEn: "Local text formatting utilities, converters, JSON tags.",
    href: "/apps",
    icon: FileText,
    keywords: ["apps", "aplicatii", "formatters"],
    category: "TOOLS",
    status: "active",
    actionLabel: "Deschide",
    actionLabelEn: "Open",
  },
  {
    id: "mortgage-calculator",
    label: "Mortgage Calculator",
    labelEn: "Mortgage Calculator",
    desc: "Calculează rata creditului și gradul maxim DTI.",
    descEn: "Simulate monthly mortgage interest and debt ratio metrics.",
    href: "/calculators",
    icon: Calculator,
    keywords: ["mortgage", "credit", "ipotecar"],
    category: "TOOLS",
    status: "active",
    actionLabel: "Calculează",
    actionLabelEn: "Calculate",
  },
  {
    id: "roi-calculator",
    label: "ROI Calculator",
    labelEn: "ROI Calculator",
    desc: "Simulează cash flow, ROI și recuperare investiție.",
    descEn: "Simulate net cash flow yields and investment paybacks.",
    href: "/calculators",
    icon: Calculator,
    keywords: ["roi", "randament", "investitie"],
    category: "TOOLS",
    status: "active",
    actionLabel: "Calculează",
    actionLabelEn: "Calculate",
  },
  {
    id: "currency-tools",
    label: "Currency Tools",
    labelEn: "Currency Tools",
    desc: "Convertor valutar BNR și m² in sq ft.",
    descEn: "BNR currency exchanges and sqm to sqft converters.",
    href: "/convenience",
    icon: Wrench,
    keywords: ["currency", "convertor", "sqm", "sqft"],
    category: "TOOLS",
    status: "active",
    actionLabel: "Deschide",
    actionLabelEn: "Open",
  },
  {
    id: "map",
    label: "GIS Map",
    labelEn: "GIS Map",
    desc: "Scanare spațială imobiliară și pin clustering.",
    descEn: "Geo-spatial real estate map audit scanner.",
    href: "/map",
    icon: Map,
    keywords: ["map", "harta", "gis", "clustering"],
    category: "TOOLS",
    status: "active",
    actionLabel: "Hartă",
    actionLabelEn: "Map",
  },
  {
    id: "osint",
    label: "OSINT Intelligence",
    labelEn: "OSINT Intelligence",
    desc: "Scaner automat de risc juridic firme și domenii.",
    descEn: "Automated business risk analysis and registry checker.",
    href: "/osint",
    icon: Eye,
    keywords: ["osint", "risc", "firme", "cautare"],
    category: "TOOLS",
    status: "active",
    actionLabel: "OSINT Scan",
    actionLabelEn: "OSINT Scan",
  },

  // ─── AI SYSTEM ─────────────────────────────────────────────────────────────
  {
    id: "brain",
    label: "AiX Brain",
    labelEn: "AiX Brain",
    desc: "Nucleul cognitiv central și motor de analiză decizională.",
    descEn: "Central decision engine routing across all platforms.",
    href: "/brain",
    icon: Brain,
    keywords: ["brain", "router", "ai", "decizional"],
    category: "AI_SYSTEM",
    status: "active",
    actionLabel: "Deschide",
    actionLabelEn: "Open",
  },
  {
    id: "money-advisor",
    label: "AI Advisor",
    labelEn: "AI Advisor",
    desc: "Consilier financiar personal ghidat de AI.",
    descEn: "AI financial advisor powered by models.",
    href: "/money-advisor",
    icon: Brain,
    keywords: ["money-advisor", "ai advisor", "chat"],
    category: "AI_SYSTEM",
    status: "active",
    actionLabel: "Consultă AI",
    actionLabelEn: "Consult AI",
  },
  {
    id: "universal-search",
    label: "Search Everything",
    labelEn: "Search Everything",
    desc: "Căutare universală rapidă pe întreaga platformă.",
    descEn: "Universal search across the entire platform via Cmd+K.",
    href: "/",
    icon: Search,
    keywords: ["search", "cautare", "cmd-k"],
    category: "AI_SYSTEM",
    status: "active",
    actionLabel: "Caută",
    actionLabelEn: "Search",
  },

  // ─── AVIATION & PRIVATE TRAVEL ─────────────────────────────────────────────
  {
    id: "private-jets",
    label: "Private Jets",
    labelEn: "Private Jets",
    desc: "VIP aircraft charter requests and tracking.",
    descEn: "VIP aircraft charter requests and tracking.",
    href: "/private-jets",
    icon: Plane,
    keywords: ["private-jets", "jet", "plane", "charter", "booking", "flight"],
    category: "LUXURY_TRAVEL",
    status: "active",
    actionLabel: "Charter request",
    actionLabelEn: "Charter request",
  },
  {
    id: "cars",
    label: "Luxury Cars",
    labelEn: "Luxury Cars",
    desc: "Chauffeur services and premium rental vehicle fleets.",
    descEn: "Chauffeur services and premium rental vehicle fleets.",
    href: "/cars",
    icon: Car,
    keywords: ["cars", "rentals", "luxury", "chauffeur", "fleet"],
    category: "LUXURY_TRAVEL",
    status: "active",
    actionLabel: "Hire vehicle",
    actionLabelEn: "Hire vehicle",
  },
  {
    id: "yachts",
    label: "Yachts Marine",
    labelEn: "Yachts Marine",
    desc: "Luxury yacht charters globally with verified captains.",
    descEn: "Luxury yacht charters globally with verified captains.",
    href: "/yachts",
    icon: Ship,
    keywords: ["yachts", "marine", "ship", "charter", "boat"],
    category: "LUXURY_TRAVEL",
    status: "active",
    actionLabel: "Book yacht",
    actionLabelEn: "Book yacht",
  },
  {
    id: "travel",
    label: "Travel Alerts",
    labelEn: "Travel Alerts",
    desc: "Ministry of Foreign Affairs (MAE) warnings & passports index.",
    descEn: "Ministry of Foreign Affairs (MAE) warnings & passports index.",
    href: "/travel",
    icon: Globe,
    keywords: ["travel", "mae", "alerts", "visa"],
    category: "LUXURY_TRAVEL",
    status: "active",
    actionLabel: "Travel Advisory",
    actionLabelEn: "Travel Advisory",
  },
  {
    id: "concierge",
    label: "Luxury Concierge",
    labelEn: "Luxury Concierge",
    desc: "Relocation assistance, UHNW lifestyle management.",
    descEn: "Relocation assistance, UHNW lifestyle management.",
    href: "/concierge",
    icon: Sparkles,
    keywords: ["concierge", "lifestyle", "hnw", "luxury"],
    category: "LUXURY_TRAVEL",
    status: "active",
    actionLabel: "Open Hub",
    actionLabelEn: "Open Hub",
  }
];

export const CONNECT_CHANNELS = [
  { id: "whatsapp", label: "WhatsApp", href: "https://wa.me/40722334455", icon: MessageCircle },
  { id: "email", label: "Email", href: "mailto:contact@cristianvaduva.com", icon: Mail },
  { id: "telegram", label: "Telegram", href: "https://t.me/AiX_OS", icon: Send },
  { id: "personal-site", label: "CristianVaduva.com", href: "https://cristianvaduva.com", icon: Globe },
  { id: "luxury-site", label: "AiXLuxury.com", href: "https://aixluxury.com", icon: Gem }
];
