import {
  Brain,
  Award,
  Building2,
  Activity,
  Coins,
  Shield,
  Scale,
  Cpu,
  Lock,
  Sparkles,
  BookOpen,
  Wrench,
  Search,
  Users,
  Compass,
  TrendingUp,
  Map,
  DollarSign,
  Newspaper,
  Eye,
  FileText,
  Gem,
  Calculator,
  MessageCircle,
  Mail,
  Send,
  Plane,
  Car,
  Ship,
  Globe,
  Network,
  type LucideIcon
} from "lucide-react";

export interface ServiceItem {
  id: string;
  label: string;
  labelEn: string;
  desc: string;
  descEn: string;
  href: string;
  icon: LucideIcon;
  keywords: string[];
  category: "BUY" | "SELL" | "INVEST" | "LEARN" | "TOOLS" | "AI_SYSTEM" | "PRICING" | "CONTACT" | "ACCOUNT";
  status: "active" | "hidden" | "beta";
  actionLabel?: string;
  actionLabelEn?: string;
  external?: boolean;
}

export const ALL_SERVICES_REGISTRY: ServiceItem[] = [
  // ─── BUY & SELL ───────────────────────────────────────────────────────────
  {
    id: "properties",
    label: "Property & Investment Hub",
    labelEn: "Property & Investment Hub",
    desc: "Catalog complet de proprietăți, investiții globale și oportunități exclusive.",
    descEn: "Complete catalog of curated premium properties, global investments, and exclusive deals.",
    href: "/proprietati",
    icon: Building2,
    keywords: ["proprietati", "properties", "apartamente", "vile", "case", "investitii", "oportunitati"],
    category: "BUY",
    status: "active",
    actionLabel: "Explorează",
    actionLabelEn: "Explore",
  },
  {
    id: "developers",
    label: "Developers",
    labelEn: "Developers",
    desc: "Profilele și ratingul de siguranță al constructorilor.",
    descEn: "Builder profiles and structural safety ratings.",
    href: "/dezvoltatori",
    icon: Users,
    keywords: ["dezvoltatori", "developers", "constructori"],
    category: "BUY",
    status: "active",
    actionLabel: "Audit",
    actionLabelEn: "Audit",
  },
  {
    id: "agencies",
    label: "Agencies",
    labelEn: "Agencies",
    desc: "Agenții de consultanță imobiliară partenere.",
    descEn: "Verified partner real estate consultancies.",
    href: "/agentii",
    icon: Compass,
    keywords: ["agentii", "agencies", "brokeri"],
    category: "BUY",
    status: "active",
    actionLabel: "Vezi",
    actionLabelEn: "View",
  },
  {
    id: "buyer-rep",
    label: "Buyer Representation",
    labelEn: "Buyer Representation",
    desc: "Consultanță dedicată exclusiv cumpărătorului.",
    descEn: "Dedicated guidance exclusively for property buyers.",
    href: "/buyer",
    icon: Compass,
    keywords: ["buyer", "rep", "cumparator"],
    category: "BUY",
    status: "active",
    actionLabel: "Angajează",
    actionLabelEn: "Hire",
  },
  {
    id: "seller-rep",
    label: "Seller Representation",
    labelEn: "Seller Representation",
    desc: "Strategii avansate de marketing și vânzare.",
    descEn: "Advanced marketing and listings sale strategies.",
    href: "/seller",
    icon: TrendingUp,
    keywords: ["seller", "vinde", "vanzator"],
    category: "SELL",
    status: "active",
    actionLabel: "Listează",
    actionLabelEn: "List",
  },

  {
    id: "private-jets",
    label: "Private Jets",
    labelEn: "Private Jets",
    desc: "Charter avioane private VIP și solicitări zbor.",
    descEn: "VIP aircraft charter requests and booking hub.",
    href: "/private-jets",
    icon: Plane,
    keywords: ["private-jets", "jet", "plane", "charter"],
    category: "BUY",
    status: "active",
    actionLabel: "Rezervă Jet",
    actionLabelEn: "Book Jet",
  },
  {
    id: "cars",
    label: "Luxury Cars",
    labelEn: "Luxury Cars",
    desc: "Mobilitate terestră premium și închirieri auto de lux.",
    descEn: "Chauffeur services and luxury vehicle rental fleet.",
    href: "/cars",
    icon: Car,
    keywords: ["cars", "rentals", "luxury", "chauffeur"],
    category: "BUY",
    status: "active",
    actionLabel: "Închiriază",
    actionLabelEn: "Rent Car",
  },
  {
    id: "yachts",
    label: "Yachts Marine",
    labelEn: "Yachts Marine",
    desc: "Charter iahturi de lux globale cu echipaj inclus.",
    descEn: "Luxury yacht charters globally with verified captains.",
    href: "/yachts",
    icon: Ship,
    keywords: ["yachts", "marine", "ship", "charter"],
    category: "BUY",
    status: "active",
    actionLabel: "Book Yacht",
    actionLabelEn: "Book Yacht",
  },
  {
    id: "concierge",
    label: "Luxury Concierge",
    labelEn: "Luxury Concierge",
    desc: "Lifestyle management HNWI și asistență relocare.",
    descEn: "Relocation assistance, UHNW lifestyle management.",
    href: "/concierge",
    icon: Sparkles,
    keywords: ["concierge", "lifestyle", "luxury"],
    category: "BUY",
    status: "active",
    actionLabel: "Explorează",
    actionLabelEn: "Explore",
  },

  // ─── INVEST & PROTECT ──────────────────────────────────────────────────────
  {
    id: "market-pulse",
    label: "Market Pulse",
    labelEn: "Market Pulse",
    desc: "Indicatori macroeconomici, analize și evoluții BNR.",
    descEn: "BNR macroeconomic indicators, analysis, and indices.",
    href: "/stiri",
    icon: Activity,
    keywords: ["market", "pulse", "stiri", "inflatie", "bnr"],
    category: "INVEST",
    status: "active",
    actionLabel: "Citește",
    actionLabelEn: "Read",
  },
  {
    id: "aix-score",
    label: "AiX Score",
    labelEn: "AiX Score",
    desc: "Rating proprietar de risc și sustenabilitate al activelor.",
    descEn: "Proprietary risk and asset safety scoring system.",
    href: "/aix-score",
    icon: Sparkles,
    keywords: ["score", "rating", "aix", "risc"],
    category: "INVEST",
    status: "active",
    actionLabel: "Vezi",
    actionLabelEn: "View",
  },

  {
    id: "private-wealth",
    label: "Private Wealth & Network",
    labelEn: "Private Wealth & Network",
    desc: "Ghiduri fiscale, optimizare taxe, rețea privată și oportunități off-market.",
    descEn: "Tax guidelines, private network, off-market opportunities.",
    href: "/private-wealth",
    icon: DollarSign,
    keywords: ["wealth", "private", "avere", "calendar", "network", "off-market"],
    category: "INVEST",
    status: "active",
    actionLabel: "Cercetează",
    actionLabelEn: "Research",
  },
  {
    id: "insurance",
    label: "Insurance",
    labelEn: "Insurance",
    desc: "Polițe de asigurare facultative și estimări de primă.",
    descEn: "Optional property insurance coverage & PAD estimates.",
    href: "/insurance",
    icon: Shield,
    keywords: ["asigurare", "insurance", "pad"],
    category: "INVEST",
    status: "active",
    actionLabel: "Calculează",
    actionLabelEn: "Calculate",
  },
  {
    id: "law",
    label: "RO Law",
    labelEn: "RO Law",
    desc: "Consultare juridică, contracte și limitări notariale.",
    descEn: "Legal framework, templates, and notary cost schedules.",
    href: "/law",
    icon: Scale,
    keywords: ["law", "lege", "legal", "notar"],
    category: "INVEST",
    status: "active",
    actionLabel: "Verifică",
    actionLabelEn: "Verify",
  },
  {
    id: "anti-teapa",
    label: "AntiȚeapă AI",
    labelEn: "AntiȚeapă AI",
    desc: "Sistem automat de de-riscare a tranzacțiilor.",
    descEn: "Automated scan mapping and risk mitigation software.",
    href: "/anti-teapa",
    icon: Shield,
    keywords: ["anti-teapa", "scanare", "litigii", "sarcini"],
    category: "INVEST",
    status: "active",
    actionLabel: "Auditează",
    actionLabelEn: "Audit",
  },



  // ─── LEARN & RESEARCH ──────────────────────────────────────────────────────
  {
    id: "books",
    label: "Books",
    labelEn: "Books",
    desc: "Recomandări de cărți de negociere și analiză macro.",
    descEn: "Recommended reading checklist for high-stakes business.",
    href: "/books",
    icon: BookOpen,
    keywords: ["books", "carti", "voss", "psychology"],
    category: "LEARN",
    status: "active",
    actionLabel: "Deschide",
    actionLabelEn: "Open",
  },
  {
    id: "learning",
    label: "Educație & Ghiduri",
    labelEn: "Learning Center",
    desc: "Cursuri și educație financiară pentru investitori.",
    descEn: "Tutorial guides and courses for strategic investors.",
    href: "/learning",
    icon: BookOpen,
    keywords: ["education", "educatie", "ghiduri"],
    category: "LEARN",
    status: "active",
    actionLabel: "Începe",
    actionLabelEn: "Start",
  },


  {
    id: "research",
    label: "Research Center",
    labelEn: "Research Center",
    desc: "Baze de date, registre publice și scanare inteligentă.",
    descEn: "State directories, public registries, and OSINT scanning.",
    href: "/research",
    icon: Globe,
    keywords: ["resurse", "resources", "linkuri", "osint", "scanare"],
    category: "LEARN",
    status: "active",
    actionLabel: "Vezi",
    actionLabelEn: "View",
  },
  {
    id: "technology",
    label: "Technology",
    labelEn: "Technology",
    desc: "API documentation, integrations, and server status.",
    descEn: "API documentation, integrations, and server status.",
    href: "/technology",
    icon: Cpu,
    keywords: ["technology", "tehnologie", "api"],
    category: "LEARN",
    status: "active",
    actionLabel: "Vezi Tech",
    actionLabelEn: "View Tech",
  },
  {
    id: "contact",
    label: "Contact",
    labelEn: "Contact",
    desc: "Hub-ul principal pentru contact, formulare și legături directe.",
    descEn: "Primary hub for contact details, forms, and direct links.",
    href: "/contact",
    icon: Mail,
    keywords: ["contact", "suport", "whatsapp", "telefon", "email"],
    category: "CONTACT",
    status: "active",
    actionLabel: "Deschide",
    actionLabelEn: "Open",
  },


  // ─── TOOLS ─────────────────────────────────────────────────────────────────



  {
    id: "convenience",
    label: "Convenience Tools",
    labelEn: "Convenience Tools",
    desc: "15 instrumente digitale practice de securitate, analiză text și calcul financiar imobiliar.",
    descEn: "15 offline-ready diagnostic tools, ROI allocators, conversions, and secure cryptography modules.",
    href: "/convenience",
    icon: Wrench,
    keywords: ["currency", "convertor", "sqm", "sqft", "calculators", "calculatoare", "notar", "ipotecar", "apps"],
    category: "TOOLS",
    status: "active",
    actionLabel: "Deschide",
    actionLabelEn: "Open",
  },



  // ─── AI SYSTEM ─────────────────────────────────────────────────────────────
  {
    id: "ecosystem",
    label: "AiX Ecosystem",
    labelEn: "AiX Ecosystem",
    desc: "Tabloul de bord complet pentru toate instrumentele AiX.",
    descEn: "Comprehensive dashboard for all AiX tools.",
    href: "/ecosystem",
    icon: LayoutDashboard,
    keywords: ["ecosystem", "aix", "dashboard", "hub"],
    category: "AI_SYSTEM",
    status: "active",
    actionLabel: "Deschide",
    actionLabelEn: "Open",
  },
  {
    id: "private-deal-room",
    label: "Private Deal Room",
    labelEn: "Private Deal Room",
    desc: "Cameră de tranzacționare privată securizată pentru clienți luxury.",
    descEn: "Secure private deal room for luxury clients & investors.",
    href: "/private-deal-room",
    icon: Lock,
    keywords: ["deal", "room", "privat", "acte", "negociere"],
    category: "INVEST",
    status: "active",
    actionLabel: "Accesează",
    actionLabelEn: "Access",
  },
  {
    id: "market-radar",
    label: "Market Radar",
    labelEn: "Market Radar",
    desc: "Harta interactivă a randamentelor și prețurilor pe zone.",
    descEn: "Interactive radar mapping premium area yields & price shifts.",
    href: "/market-radar",
    icon: Globe,
    keywords: ["radar", "harta", "zone", "cluj", "bucuresti"],
    category: "INVEST",
    status: "active",
    actionLabel: "Urmărește",
    actionLabelEn: "Track",
  },
  {
    id: "simulation",
    label: "Future Simulation",
    labelEn: "Future Simulation",
    desc: "Simulator de portofoliu imobiliar și alocare de capital strategic.",
    descEn: "Strategic property portfolio simulator and capital allocation.",
    href: "/simulation",
    icon: Calculator,
    keywords: ["simulator", "simulare", "capital", "avere", "wealth"],
    category: "TOOLS",
    status: "active",
    actionLabel: "Simulează",
    actionLabelEn: "Simulate",
  },
  {
    id: "newsroom",
    label: "Intelligence Newsroom",
    labelEn: "Intelligence Newsroom",
    desc: "Flux AI-powered de rapoarte macroeconomice și rezumate.",
    descEn: "AI-powered stream of macroeconomic reports and summaries.",
    href: "/newsroom",
    icon: Activity,
    keywords: ["newsroom", "stiri", "rapoarte", "feed", "sumar"],
    category: "LEARN",
    status: "active",
    actionLabel: "Deschide",
    actionLabelEn: "Open",
  },
  {
    id: "agents",
    label: "AiX OS™ AI Agents",
    labelEn: "AiX OS™ AI Agents",
    desc: "Rețeaua noastră de agenți autonomi analizează piața 24/7.",
    descEn: "Our network of autonomous agents analyzing the market 24/7.",
    href: "/agents",
    icon: Cpu,
    keywords: ["agents", "ai", "autonomous", "market", "agent"],
    category: "AI_SYSTEM",
    status: "active",
    actionLabel: "Vezi Agenții",
    actionLabelEn: "View Agents",
  },
];

export const CONNECT_CHANNELS = [
  { id: "whatsapp", label: "WhatsApp", href: "https://wa.me/436509536345", icon: MessageCircle },
  { id: "email", label: "Email", href: "mailto:cristianvaduva@duck.com", icon: Mail },
  { id: "telegram", label: "Telegram", href: "https://t.me/AiX_OS", icon: Send },
  { id: "personal-site", label: "CristianVaduva.com", href: "https://cristianvaduva.com", icon: Globe },
  { id: "luxury-site", label: "AiXLuxury.com", href: "https://aixluxury.com", icon: Gem }
];
