import {
  Brain,
  Building2,
  Activity,
  Coins,
  Shield,
  Scale,
  Cpu,
  Lock,
  Sparkles,
  BookOpen,
  Wrench,
  Search,
  Users,
  Compass,
  TrendingUp,
  Map,
  DollarSign,
  Newspaper,
  Eye,
  Plane,
  Car,
  Ship,
  Globe,
  Network,
  FileText,
  Gem,
  ShieldAlert,
  FileWarning,
  Sliders,
  Calculator,
  MessageCircle,
  Mail,
  Send,
  type LucideIcon
} from "lucide-react";

export interface ServiceItem {
  id: string;
  label: string;
  labelEn: string;
  desc: string;
  descEn: string;
  href: string;
  icon: LucideIcon;
  keywords: string[];
  category: "BUY_SELL_DISCOVER" | "INVEST_PROTECT" | "LEARN_RESEARCH" | "TOOLS" | "CONNECT";
  actionLabel?: string;
  actionLabelEn?: string;
  external?: boolean;
}

export const ALL_SERVICES_REGISTRY: ServiceItem[] = [
  // ─── BUY • SELL • DISCOVER ────────────────────────────────────────────────
  {
    id: "properties",
    label: "Proprietăți",
    labelEn: "Properties",
    desc: "Catalog complet de proprietăți premium selectate.",
    descEn: "Complete catalog of curated premium properties.",
    href: "/proprietati",
    icon: Building2,
    keywords: ["proprietati", "properties", "apartamente", "vile", "case", "apartament", "villa", "casa"],
    category: "BUY_SELL_DISCOVER",
    actionLabel: "Vezi Oferte",
    actionLabelEn: "View Offers",
  },
  {
    id: "buyer-rep",
    label: "Buyer Representation",
    labelEn: "Buyer Representation",
    desc: "Asistență exclusivă și consultanță dedicată la achiziție.",
    descEn: "Exclusive guidance and dedicated consultancy for buying.",
    href: "/buyer",
    icon: Compass,
    keywords: ["buyer", "rep", "cumparator", "asistenta", "broker", "negotiation"],
    category: "BUY_SELL_DISCOVER",
    actionLabel: "Angajează Broker",
    actionLabelEn: "Hire Broker",
  },
  {
    id: "seller-rep",
    label: "Seller Representation",
    labelEn: "Seller Representation",
    desc: "Strategii avansate de promovare și vânzare a activelor.",
    descEn: "Advanced marketing and exclusive listing strategies.",
    href: "/seller",
    icon: TrendingUp,
    keywords: ["seller", "vinde", "vanzator", "listare", "promovare"],
    category: "BUY_SELL_DISCOVER",
    actionLabel: "Listează Activ",
    actionLabelEn: "List Asset",
  },
  {
    id: "luxury-properties",
    label: "Proprietăți Luxury",
    labelEn: "Luxury Properties",
    desc: "Portofoliu exclusiv de vile și penthouse-uri de lux.",
    descEn: "Exclusive portfolio of luxury villas and penthouses.",
    href: "/proprietati?type=luxury",
    icon: Gem,
    keywords: ["luxury", "lux", "premium", "exclusiv", "penthouse", "vila lux"],
    category: "BUY_SELL_DISCOVER",
    actionLabel: "Explorează",
    actionLabelEn: "Explore",
  },
  {
    id: "off-market",
    label: "Off-Market",
    labelEn: "Off-Market",
    desc: "Tranzacții discrete securizate sub acord strict NDA.",
    descEn: "Discrete secure transactions under strict NDA.",
    href: "/off-market",
    icon: Lock,
    keywords: ["off-market", "secret", "confidential", "discrete", "nda", "deals"],
    category: "BUY_SELL_DISCOVER",
    actionLabel: "Accesează Portale",
    actionLabelEn: "Access Portals",
  },
  {
    id: "developers",
    label: "Dezvoltatori imobiliari",
    labelEn: "Real Estate Developers",
    desc: "Baza de date cu profilele și ratingul constructorilor.",
    descEn: "Database of builder profiles and safety ratings.",
    href: "/dezvoltatori",
    icon: Users,
    keywords: ["dezvoltatori", "developers", "constructori", "one united", "emaar"],
    category: "BUY_SELL_DISCOVER",
    actionLabel: "Audit Dezvoltatori",
    actionLabelEn: "Audit Developers",
  },
  {
    id: "agencies",
    label: "Agenții Imobiliare",
    labelEn: "Real Estate Agencies",
    desc: "Companii de consultanță imobiliară verificate și licențiate.",
    descEn: "Curated list of verified licensed real estate consultancies.",
    href: "/agentii",
    icon: Compass,
    keywords: ["agentii", "agencies", "brokeri", "partner", "chestertons"],
    category: "BUY_SELL_DISCOVER",
    actionLabel: "Vezi Agenții",
    actionLabelEn: "View Agencies",
  },
  {
    id: "neighborhood-intel",
    label: "Neighborhood Intelligence",
    labelEn: "Neighborhood Intelligence",
    desc: "Analiză detaliată a zonelor premium și rating regional.",
    descEn: "In-depth analytics on premium zones and regional scoring.",
    href: "/aix-score",
    icon: Map,
    keywords: ["neighborhood", "intel", "cartier", "zona", "rating", "score"],
    category: "BUY_SELL_DISCOVER",
    actionLabel: "Vezi Rating Zonă",
    actionLabelEn: "View Zone Rating",
  },
  {
    id: "property-scanner",
    label: "Property Scanner",
    labelEn: "Property Scanner",
    desc: "Audit tehnic, litigii și verificări de sarcini pe extras.",
    descEn: "Technical audits, active court claims, and lien checks.",
    href: "/anti-teapa",
    icon: ShieldAlert,
    keywords: ["scanner", "verificare", "sarcini", "litigii", "extrase", "carte funciara"],
    category: "BUY_SELL_DISCOVER",
    actionLabel: "Scanează Carte Funciară",
    actionLabelEn: "Scan Cadastre",
  },
  {
    id: "ai-valuation",
    label: "AI Valuation",
    labelEn: "AI Valuation",
    desc: "Estimare valoare de piață bazată pe tranzacții reale.",
    descEn: "Estimated market value calculated from actual transactions.",
    href: "/valuation",
    icon: Scale,
    keywords: ["valuation", "evaluare", "pret", "estimare", "valoare", "mp util"],
    category: "BUY_SELL_DISCOVER",
    actionLabel: "Calculează Valoare",
    actionLabelEn: "Calculate Value",
  },

  // ─── INVEST • PROTECT ──────────────────────────────────────────────────────
  {
    id: "market-pulse",
    label: "Market Pulse",
    labelEn: "Market Pulse",
    desc: "Analiză macro, evoluții și știri imobiliare zilnice.",
    descEn: "Macroeconomics, trends, and daily transaction news.",
    href: "/stiri",
    icon: Activity,
    keywords: ["market", "pulse", "stiri", "analize", "nivele", "macro"],
    category: "INVEST_PROTECT",
    actionLabel: "Citește Analize",
    actionLabelEn: "Read Insights",
  },
  {
    id: "aix-score",
    label: "AiX Score",
    labelEn: "AiX Score",
    desc: "Scorul proprietar de siguranță și randament al activelor.",
    descEn: "Proprietary safety and yield score for assets.",
    href: "/aix-score",
    icon: Sparkles,
    keywords: ["score", "rating", "aix", "siguranta", "risc", "calitate"],
    category: "INVEST_PROTECT",
    actionLabel: "Verifică Scorul",
    actionLabelEn: "Verify Score",
  },
  {
    id: "private-wealth",
    label: "Private Wealth",
    labelEn: "Private Wealth",
    desc: "Indicatori de avere globali și calendar economic premium.",
    descEn: "Global net worth benchmarks and elite calendar event list.",
    href: "/wealth",
    icon: DollarSign,
    keywords: ["wealth", "private", "avere", "calendar", "forbes", "wealth-desk"],
    category: "INVEST_PROTECT",
    actionLabel: "Accesează Wealth Desk",
    actionLabelEn: "Access Wealth Desk",
  },
  {
    id: "investments",
    label: "Investments",
    labelEn: "Investments",
    desc: "Managementul portofoliilor de active HNWI și ETF-uri.",
    descEn: "Management of HNWI assets, crypto, and global stocks.",
    href: "/investments",
    icon: Coins,
    keywords: ["investments", "investitii", "portofoliu", "actiuni", "crypto", "etf", "gold"],
    category: "INVEST_PROTECT",
    actionLabel: "Vezi Portofolii",
    actionLabelEn: "View Portfolios",
  },
  {
    id: "insurance",
    label: "Insurance",
    labelEn: "Insurance",
    desc: "PAD și polițe facultative pentru locuințe exclusiviste.",
    descEn: "PAD and optional property insurance analysis & quotes.",
    href: "/insurance",
    icon: Shield,
    keywords: ["insurance", "asigurari", "pad", "facultativa", "politie", "broker"],
    category: "INVEST_PROTECT",
    actionLabel: "Calculează Poliță",
    actionLabelEn: "Calculate Premium",
  },
  {
    id: "law",
    label: "RO Law",
    labelEn: "RO Law",
    desc: "Cadru legislativ, taxe notariale și asistență juridică.",
    descEn: "Romanian legal framework, notary fees, and litigation checks.",
    href: "/law",
    icon: Scale,
    keywords: ["law", "lege", "legal", "notar", "taxa", "intabulare", "anpc", "contracte"],
    category: "INVEST_PROTECT",
    actionLabel: "Consultanță Juridică",
    actionLabelEn: "Legal Counsel",
  },
  {
    id: "anti-teapa",
    label: "AntiȚeapă AI",
    labelEn: "Anti-Fraud AI",
    desc: "Sistem automat de de-riscare a achizițiilor imobiliare.",
    descEn: "Automated risk mitigation and fraud prevention for buyers.",
    href: "/anti-teapa",
    icon: Shield,
    keywords: ["anti-teapa", "frauda", "trazactie", "verificare", "siguranta", "vicii"],
    category: "INVEST_PROTECT",
    actionLabel: "Auditează Tranzacție",
    actionLabelEn: "Audit Deal",
  },
  {
    id: "market-intelligence",
    label: "Market Intelligence",
    labelEn: "Market Intelligence",
    desc: "Rate de schimb BNR live, inflație, dobândă și commodities.",
    descEn: "Live BNR exchange rates, key policy rates, CPI, and gold spot.",
    href: "/market",
    icon: TrendingUp,
    keywords: ["bnr", "dobanda", "curs", "aur", "commodities", "spot", "market-intel"],
    category: "INVEST_PROTECT",
    actionLabel: "Vezi Indicatori",
    actionLabelEn: "View Indicators",
  },

  // ─── LEARN • RESEARCH ──────────────────────────────────────────────────────
  {
    id: "money-advisor",
    label: "AI Advisor",
    labelEn: "AI Advisor",
    desc: "Consilier financiar personal ghidat de inteligență artificială.",
    descEn: "Personal financial advisor driven by artificial intelligence.",
    href: "/money-advisor",
    icon: Brain,
    keywords: ["money-advisor", "chat", "consilier", "sfat", "financiar", "portofoliu ai", "ai advisor"],
    category: "LEARN_RESEARCH",
    actionLabel: "Discută cu AI",
    actionLabelEn: "Consult AI",
  },
  {
    id: "books",
    label: "Books",
    labelEn: "Books",
    desc: "Selecție de literatură fundamentală despre investiții și mindset.",
    descEn: "Fundamental reading list on wealth creation and economics.",
    href: "/books",
    icon: BookOpen,
    keywords: ["books", "carti", "lectura", "keller", "voss", "dalio", "housel"],
    category: "LEARN_RESEARCH",
    actionLabel: "Explorează Cărți",
    actionLabelEn: "Explore Books",
  },
  {
    id: "learning",
    label: "Education",
    labelEn: "Education",
    desc: "Ghiduri pas-cu-pas, checklists de tranzacționare și taxe.",
    descEn: "Step-by-step transaction guides, checklists, and tax models.",
    href: "/learning",
    icon: BookOpen,
    keywords: ["learning", "educatie", "ghid", "cumparare", "taxe anaf", "negociere"],
    category: "LEARN_RESEARCH",
    actionLabel: "Începe Studiul",
    actionLabelEn: "Start Learning",
  },
  {
    id: "guides",
    label: "Guides",
    labelEn: "Guides",
    desc: "Ghiduri tranzacționale complete și modele de documente.",
    descEn: "Detailed transaction guide resources and dynamic document checklists.",
    href: "/learning",
    icon: BookOpen,
    keywords: ["guides", "ghiduri", "learning", "documente", "ajutor"],
    category: "LEARN_RESEARCH",
    actionLabel: "Vezi Ghiduri",
    actionLabelEn: "View Guides",
  },
  {
    id: "resources",
    label: "Resources",
    labelEn: "Resources",
    desc: "Utilitare externe, portaluri guvernamentale și instrumente utile.",
    descEn: "External databases, governmental sites, and investor directories.",
    href: "/resources",
    icon: Globe,
    keywords: ["resources", "resurse", "linkuri", "portaluri", "utilitati"],
    category: "LEARN_RESEARCH",
    actionLabel: "Vezi Resurse",
    actionLabelEn: "View Resources",
  },
  {
    id: "technology",
    label: "Technology",
    labelEn: "Technology",
    desc: "Soluții tech, configurări de securitate și API developer.",
    descEn: "Developer integrations, API structures, and cybersecurity checklists.",
    href: "/technology",
    icon: Cpu,
    keywords: ["technology", "tehnologie", "api", "developer", "config", "github"],
    category: "LEARN_RESEARCH",
    actionLabel: "Tehnologie",
    actionLabelEn: "Technology Info",
  },
  {
    id: "cybersecurity",
    label: "Cybersecurity",
    labelEn: "Cybersecurity",
    desc: "Prevenirea fraudelor online, audit securitate rețea și parole.",
    descEn: "Fraud prevention, credentials check, and secure browsing tips.",
    href: "/cybersecurity",
    icon: Lock,
    keywords: ["cybersecurity", "securitate", "parole", "phishing", "scam", "vpn"],
    category: "LEARN_RESEARCH",
    actionLabel: "Verifică Securitate",
    actionLabelEn: "Verify Security",
  },
  {
    id: "travel",
    label: "Travel",
    labelEn: "Travel",
    desc: "Alerte de călătorie MAE, pașaport index și zboruri private.",
    descEn: "MAE travel alerts, passport index lookup, and private jet charter info.",
    href: "/travel",
    icon: Globe,
    keywords: ["travel", "calatorii", "mae", "pasaport", "viza", "charter"],
    category: "LEARN_RESEARCH",
    actionLabel: "Informații Călătorii",
    actionLabelEn: "Travel Info",
  },
  {
    id: "apps",
    label: "Open Apps",
    labelEn: "Open Apps",
    desc: "Utilitare locale de prelucrare text, JSON și calculatoare.",
    descEn: "Developer utilities: JSON formatter, Markdown, CSV, and converters.",
    href: "/apps",
    icon: FileText,
    keywords: ["apps", "aplicatii", "markdown", "json", "csv", "converters"],
    category: "LEARN_RESEARCH",
    actionLabel: "Deschide Aplicații",
    actionLabelEn: "Open Apps",
  },

  // ─── TOOLS ─────────────────────────────────────────────────────────────────
  {
    id: "universal-search",
    label: "Universal Search",
    labelEn: "Universal Search",
    desc: "Căutare universală pe întreaga platformă cu Cmd+K.",
    descEn: "Universal search across the entire platform via Cmd+K.",
    href: "/",
    icon: Search,
    keywords: ["search", "cautare", "global", "universal", "find", "cmd-k"],
    category: "TOOLS",
    actionLabel: "Caută",
    actionLabelEn: "Search",
  },
  {
    id: "calculators",
    label: "Calculators",
    labelEn: "Calculators",
    desc: "Calcul rate credit, ROI imobiliar, yield chirie și taxe notariale.",
    descEn: "Mortgage estimators, ROI simulators, rental yield, and notary cost checks.",
    href: "/calculators",
    icon: Calculator,
    keywords: ["calculators", "calculatoare", "ipotecar", "dobanda", "notar", "yield"],
    category: "TOOLS",
    actionLabel: "Calculează Scenarii",
    actionLabelEn: "Calculate Scenarios",
  },
  {
    id: "document-tools",
    label: "Document Tools",
    labelEn: "Document Tools",
    desc: "Analiză automată contracte imobiliare, extrase de CF și scanare OCR.",
    descEn: "Automated real estate contracts auditor, floor plan OCR, and summaries.",
    href: "/document-intelligence",
    icon: FileText,
    keywords: ["document", "intel", "ocr", "pdf", "contract", "scan", "scanare"],
    category: "TOOLS",
    actionLabel: "Încarcă Document",
    actionLabelEn: "Upload Document",
  },
  {
    id: "mortgage-calculator",
    label: "Mortgage Calculator",
    labelEn: "Mortgage Calculator",
    desc: "Calculează ratele lunare de rambursat și gradul maxim de îndatorare.",
    descEn: "Estimate monthly mortgage payments and debt-to-income limits.",
    href: "/calculators",
    icon: Calculator,
    keywords: ["mortgage", "credit", "ipotecar", "calculator rata", "dobanda"],
    category: "TOOLS",
    actionLabel: "Calculează Ipotecă",
    actionLabelEn: "Calculate Mortgage",
  },
  {
    id: "roi-calculator",
    label: "ROI Calculator",
    labelEn: "ROI Calculator",
    desc: "Calculează randamentul return-on-investment și recuperarea capitalului.",
    descEn: "Calculate Return on Investment percentage and payback period.",
    href: "/calculators",
    icon: Calculator,
    keywords: ["roi", "investitie", "randament", "profit", "recuperare capital"],
    category: "TOOLS",
    actionLabel: "Calculează ROI",
    actionLabelEn: "Calculate ROI",
  },
  {
    id: "rental-yield",
    label: "Rental Yield",
    labelEn: "Rental Yield",
    desc: "Calculează randamentul brut și net obținut din chirii.",
    descEn: "Calculate gross and net rental yields for investment properties.",
    href: "/calculators",
    icon: Calculator,
    keywords: ["rental", "yield", "chirie", "randament chirie", "incasari"],
    category: "TOOLS",
    actionLabel: "Calculează Yield",
    actionLabelEn: "Calculate Yield",
  },
  {
    id: "notary-fees",
    label: "Notary Fees",
    labelEn: "Notary Fees",
    desc: "Calculează taxele notariale, intabularea și impozitul imobiliar.",
    descEn: "Estimate notary fees, land registry taxes, and property transaction taxes.",
    href: "/calculators",
    icon: Calculator,
    keywords: ["notary", "notar", "taxe", "intabulare", "onorariu", "tva"],
    category: "TOOLS",
    actionLabel: "Calculează Taxe",
    actionLabelEn: "Calculate Fees",
  },
  {
    id: "insurance-estimator",
    label: "Insurance Estimator",
    labelEn: "Insurance Estimator",
    desc: "Calculează estimativ valoarea poliței obligatorii și facultative.",
    descEn: "Estimate estimated mandatory PAD and optional home insurance premiums.",
    href: "/insurance",
    icon: Shield,
    keywords: ["estimator", "asigurare", "pret asigurare", "prima", "pad estimare"],
    category: "TOOLS",
    actionLabel: "Estimează Cost",
    actionLabelEn: "Estimate Premium",
  },
  {
    id: "currency-converter",
    label: "Currency Converter",
    labelEn: "Currency Converter",
    desc: "Convertor valutar de referință cu rata BNR curentă.",
    descEn: "Reference currency exchanges updated with current BNR exchange rates.",
    href: "/convenience",
    icon: Wrench,
    keywords: ["currency", "convertor valutar", "ron eur", "curs bnr"],
    category: "TOOLS",
    actionLabel: "Convertește",
    actionLabelEn: "Convert",
  },
  {
    id: "government-resources",
    label: "Useful Government Resources",
    labelEn: "Useful Government Resources",
    desc: "Registre publice și portaluri guvernamentale oficiale.",
    descEn: "Direct access directories for official state and cadastre agencies.",
    href: "/osint",
    icon: Eye,
    keywords: ["government", "guvern", "ancpi", "anaf", "just", "onrc"],
    category: "TOOLS",
    actionLabel: "Vezi Portaluri",
    actionLabelEn: "View Portals",
  },

  // ─── CONNECT ───────────────────────────────────────────────────────────────
  {
    id: "whatsapp",
    label: "WhatsApp",
    labelEn: "WhatsApp",
    desc: "Conexiune directă prin chat securizat.",
    descEn: "Direct secure message room.",
    href: "https://wa.me/40722334455",
    icon: MessageCircle,
    keywords: ["whatsapp", "chat", "mesaj", "telefon"],
    category: "CONNECT",
    external: true,
  },
  {
    id: "email",
    label: "Email",
    labelEn: "Email",
    desc: "Tragere cereri direct la contact@cristianvaduva.com",
    descEn: "Inquiries direct to contact@cristianvaduva.com",
    href: "mailto:contact@cristianvaduva.com",
    icon: Mail,
    keywords: ["email", "mail", "adresa", "contact"],
    category: "CONNECT",
    external: true,
  },
  {
    id: "telegram",
    label: "Telegram",
    labelEn: "Telegram",
    desc: "Notificări instantanee pe canalul oficial.",
    descEn: "Instant push announcements on official channel.",
    href: "https://t.me/AiX_OS",
    icon: Send,
    keywords: ["telegram", "chat", "canal", "grup"],
    category: "CONNECT",
    external: true,
  },
  {
    id: "instagram",
    label: "Instagram",
    labelEn: "Instagram",
    desc: "Noutăți vizuale din portofoliul luxury.",
    descEn: "Visual announcements from luxury market.",
    href: "https://instagram.com/cristian_vaduva_cristianv",
    icon: Globe,
    keywords: ["instagram", "social", "media", "poze"],
    category: "CONNECT",
    external: true,
  },
  {
    id: "linkedin",
    label: "LinkedIn",
    labelEn: "LinkedIn",
    desc: "Conexiuni de business corporative.",
    descEn: "Corporate networking hub.",
    href: "https://www.linkedin.com/in/cristianv%C4%83duva",
    icon: Globe,
    keywords: ["linkedin", "professional", "business", "retea"],
    category: "CONNECT",
    external: true,
  },
  {
    id: "facebook",
    label: "Facebook",
    labelEn: "Facebook",
    desc: "Pagina oficială de comunitate.",
    descEn: "Official community board page.",
    href: "https://www.facebook.com/CristianVaduvaCV",
    icon: Globe,
    keywords: ["facebook", "social", "comunitate"],
    category: "CONNECT",
    external: true,
  },
  {
    id: "youtube",
    label: "YouTube",
    labelEn: "YouTube",
    desc: "Analize imobiliare și prezentări video.",
    descEn: "Market analysis and asset video tours.",
    href: "https://youtube.com/@CristianVaduvaCV",
    icon: Globe,
    keywords: ["youtube", "video", "analiza", "tururi"],
    category: "CONNECT",
    external: true,
  },
  {
    id: "personal-site",
    label: "CristianVaduva.com",
    labelEn: "CristianVaduva.com",
    desc: "Portofoliul personal de inginerie și investiții.",
    descEn: "Personal investments and engineering portfolio.",
    href: "https://cristianvaduva.com",
    icon: Globe,
    keywords: ["personal", "site", "creativ", "fondator"],
    category: "CONNECT",
    external: true,
  },
  {
    id: "luxury-site",
    label: "AiXLuxury.com",
    labelEn: "AiXLuxury.com",
    desc: "Portal exclusiv de brokeraj de lux.",
    descEn: "Exclusives luxury listing marketplace.",
    href: "https://aixluxury.com",
    icon: Gem,
    keywords: ["luxury", "site", "brokeraj", "lux", "portofoliu"],
    category: "CONNECT",
    external: true,
  },
  {
    id: "linktree",
    label: "Linktree",
    labelEn: "Linktree",
    desc: "Baza de scurtături și profile sociale agregate.",
    descEn: "Profile links aggregate social bookmarks.",
    href: "https://linktr.ee/cristianvaduva",
    icon: Users,
    keywords: ["linktree", "bookmarks", "scurtaturi", "direct"],
    category: "CONNECT",
    external: true,
  }
];
